### ISSUE TITLE
Mailchimp 2.0 Api

### ISSUE THREAD

**Issue by Anton-Interon** [cgarnier/angular-mailchimp-subscribe#1]
Hi 

I want to pick your brain a bit.

In angular api 2.0 they are expecting a structure for email and merge_vars.

Your code amended as follows but the api still returns an error
"status":"error","code":-100,"name":"ValidationError","error":"Validation error: {\"email\":\"Please enter a struct\\/associative array\",\"merge_vars\":\"Please enter a struct\\/associative array\"}"}

 .provider('CgMailChimpService', function () {
        var config = { username: '', dc: '', u: '', id: '' };

```
    this.setConfig = function (cfg) {
        config = cfg;
    };

    this.$get = function ($http, $q) {

        var url = 'https://' + config.dc + '.api.mailchimp.com/2.0/lists/subscribe';
        var params = [];

        return {
            subscribe: function (data) {
                var defer = $q.defer();
                var params = angular.extend({}, {
                        apikey: config.u,
                        id: config.id,
                        email: [{
                            email: data.EMAIL,
                            euid: '1',
                            leid: '2'

                        }],
                        merge_vars: [{
                            FNAME: data.FNAME,
                            LNAME: data.SNAME

                        }],
                        email_type: "html",
                        send_welcome: true
                    }    )       
                ;
                $http({
                    url: url,
                    params: params,
                    method: 'JSONP',

                }).then(function (data) {
                    if (data.data.result === 'success')
                        defer.resolve(data.data);
                    else
                        defer.reject(data.data);

                }, function (err) {
                    defer.reject(err)
                });

                return defer.promise;
            }
        }
    }
});
```

**Comment by cgarnier** [comment]
Hello,
It s not a good idea to use your api key in a client side application because it s expected to be secret. If you want to use the api, you should do it from a server app. 
Anyone who can get your api key can steal your data and fucked up your account so put it in plain text in a js file is not recommended. 

The <key> used in my script is not the api key. I dont really know what is it. Maybe user id or something. You can get it in the signup form exemples.

**Comment by Anton-Interon** [comment]
Thanks
