### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Martinsos** [cgarnier/angular-mailchimp-subscribe#2]
How secure is this approach to use mailchimp? With API key anybody can do what they want. If they could just add emails that would not be so terrible, but I believe they can also remove existing emails and so on?

**Comment by cgarnier** [comment]
Hey,
This module don't use api key. It use the same approach of their ajax exemples. The key refer to your user account and is not an api key.
If you want use their api you have to do this on server side.

**Comment by cgarnier** [comment]
https://us10.admin.mailchimp.com/lists/

choose your list, click on signup from, click on embedded form. In the code you will find the post url.

```
<form action=" http://<username>.<dc>.list-manage1.com/subscribe/post?u=<u>&id=<id>"
```

Next, you just have to settup the module with this data

```
angular.module('app', ['cg.mailchimp'])
.config(function (CgMailChimpServiceProvider) {

    CgMailChimpServiceProvider.setConfig({
            username: '<username>',
            dc: '<dc>',
            u: '<u>',
            id:'<id>>'
        });
})
```

If you find a bettrer way to retrieve this infos, let me knows.

**Comment by Martinsos** [comment]
Aha I see, thank you! Nice module by the way :).
This way user has to do a double-opt process if I am correct? If yes, did you find any way to get single-opt process to work? I am working on subscribtion landing page and double-opt sounds like too much trouble for users.

**Comment by cgarnier** [comment]
Yes it should be a double opt-process. I dont know how to disable that. But you can remove this module and use directly the mailchimp api on your server to add user directly :P

**Comment by Martinsos** [comment]
Great, thanks! Yes I will probably to that at the end, but I was hoping to avoid having any backend at all :) and do it all from client.

**Comment by cgarnier** [comment]
I close this. Good luck with your project =)

**Comment by Martinsos** [comment]
Thanks :)!

**Comment by philippetheis** [comment]
@Martinsos, Have you found a way to disable the double-optin in the meantime?
I have the same issue, our users should not confirm the coming soon signup.
There is a posibillity in the mailchimp API to disable it: `"double_optin": false`
But I have no idea how to do it with this library

thanks

**Comment by Martinsos** [comment]
@philippetheis Not unfortunately! You can do it as @cgarnier suggested, by implementing direct adding to mailchimp list through backend.

**Comment by philippetheis** [comment]
ok. Thanks a lot!
